### ISSUE TITLE
Private Key file entfernen ASAP

### ISSUE THREAD

**Issue by jepetko** [LukasMock/REMME_start#1]
bitte die Datei Remme_SSH_KEY_MUI_IMPORTANTE von der git entfernen. Nur .pub-Keys (public ssh key) sind öffentlich wie der Name schon sagt. Wenn jemand den private key hat, kann er die verschlüsselte Kommunikation entschlüsseln.

Bitte beachte, dass wenn 1x schon was unter Versionskontrolle war, kann man immer wieder auf den jeweiligen Commit und somit auf die Datei zurückgreifen.

Die Datei bitte so in die .gitignore hinzufügen (bzw händisch im Editor):

```sh
echo Remme_SSH_KEY_MUI_IMPORTANTE >> .gitignore
```
Warum sind die Files überhaupt eingecheckt?

**Comment by LukasMock** [comment]
Sind entfernt, hab nur alles mal rauf gepusht weil ich es nicht hinbekommen habe das repo private zu machen und über die ssh Verbindung rauf zu pushen...
Daher habe ich das initiale Repo mal public gemacht und hätte später erst geändert da hier nur mal ein um eine ionic start app handelt ohne spezifischen content. Hätte ohnehin einen neuen Schlüssel dann generieren wollen daher hab ich es mal so gelassen.
Danke dir auf jeden Fall das du mal rein geschaut hast :)

**Comment by jepetko** [comment]
Du musst das public key auf github deployen. Sie auch
https://help.github.com/en/articles/connecting-to-github-with-ssh

LukasMock <notifications@github.com> schrieb am Mo., 25. März 2019, 18:38:
